blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/orgs/arcadelabs/discussions/categories/ideas
    about: Request for specific features/content addition here.
  - name: Discord community
    url: https://discord.gg/arcadelabs
    about: Join our Discord support server.
